# -*- coding: utf-8 -*-
"""Proyek Analisis Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ug4Ox4qIFDSo1koFA0XiNJE-ce12rECy

# Proyek Analisis Data: [Input Nama Dataset]
- **Nama:** [aditya putra afendi]
- **Email:** [m200b4ky0113@bangkit.academy]
- **ID Dicoding:** [M200B4KY0113]

## Menentukan Pertanyaan Bisnis

- Bagaimana pengaruh cuaca terhadap jumlah peminjaman sepeda harian?
- Bagaimana pola peminjaman sepeda pada jam-jam tertentu dalam satu hari?

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""## Data Wrangling

### Gathering Data
"""

# Load the datasets from /mnt/data
day_df = pd.read_csv('/mnt/data/day.csv')
hour_df = pd.read_csv('/mnt/data/hour.csv')

# Display the first few rows of each dataset
day_df.head(), hour_df.head()

"""**Insight:**
- Dataset day.csv berisi data harian dengan informasi seperti cuaca, suhu, dan jumlah pengguna sepeda.
- Dataset hour.csv berisi data per jam dengan informasi yang lebih rinci seperti waktu peminjaman dan cuaca.

### Assessing Data
"""

# Get basic information about the datasets
day_df.info()
hour_df.info()

# Check for missing values
day_df.isnull().sum()
hour_df.isnull().sum()

"""**Insight:**
- Tidak ada nilai kosong di kedua dataset.
- Kolom dteday bertipe objek, perlu diubah menjadi tipe datetime untuk memudahkan analisis.

### Cleaning Data
"""

try:
    day_df['dteday'] = pd.to_datetime(day_df['dteday'])
    hour_df['dteday'] = pd.to_datetime(hour_df['dteday'])
except ValueError as e:
    print(f"Error converting 'dteday' to datetime: {e}")

    # Check unique values in the 'dteday' column to identify incorrect values
    print("Unique values in 'hour_df[dteday]':", hour_df['dteday'].unique())

"""**Insight:**
- Kolom dteday berhasil diubah menjadi format datetime untuk kedua dataset.
- Data siap untuk eksplorasi lebih lanjut.

## Exploratory Data Analysis (EDA)

### Explore ...
"""

# Summary statistics for day and hour datasets
day_df.describe()
hour_df.describe()

# Visualizing the distribution of total bike rentals in the daily dataset
sns.histplot(day_df['cnt'], kde=True)
plt.title('Distribusi Jumlah Peminjaman Sepeda Harian')
plt.xlabel('Jumlah Peminjaman')
plt.ylabel('Frekuensi')
plt.show()

"""**Insight:**
- Sebagian besar peminjaman sepeda terjadi dalam rentang tertentu yang dapat diamati dari distribusi.

## Visualization & Explanatory Analysis

### Pertanyaan 1:
"""

# Analyzing the effect of weather on daily bike rentals
sns.boxplot(x='weathersit', y='cnt', data=day_df)
plt.title('Pengaruh Cuaca terhadap Jumlah Peminjaman Sepeda Harian')
plt.xlabel('Kondisi Cuaca')
plt.ylabel('Jumlah Peminjaman')
plt.show()

"""### Pertanyaan 2:"""

# Analyzing hourly rental patterns
# Select only numeric columns for aggregation
hourly_avg = hour_df.groupby('hr').mean(numeric_only=True).reset_index()

# Plotting the hourly rental patterns
sns.lineplot(x='hr', y='cnt', data=hourly_avg)
plt.title('Pola Peminjaman Sepeda pada Berbagai Jam dalam Sehari')
plt.xlabel('Jam')
plt.ylabel('Rata-rata Jumlah Peminjaman')
plt.show()

"""**Insight:**
- Pertanyaan 1: Kondisi cuaca berpengaruh terhadap jumlah peminjaman, di mana cuaca yang lebih baik cenderung meningkatkan jumlah peminjaman.
- Pertanyaan 2: Ada pola penggunaan sepeda yang meningkat pada jam-jam sibuk seperti pagi dan sore hari.

## Analisis Lanjutan (Opsional)
"""



"""## Conclusion

- Conclution pertanyaan 1: Kondisi cuaca sangat mempengaruhi jumlah peminjaman sepeda. Cuaca cerah meningkatkan peminjaman, sedangkan cuaca buruk menurunkannya.

- Conclution pertanyaan 2: Peminjaman sepeda memiliki pola yang jelas, dengan puncak terjadi pada jam sibuk pagi dan sore hari, menunjukkan penggunaan untuk perjalanan kerja atau sekolah.
"""